name: "Hello world workflow"

# Controls when the action will run.
on:
    push:
        branches:
            - main
            - production

            jobs:
                hello_world:
                    runs-on: ubintu-latest
                    steps:
                        - name: "print hello world"
                            run: echo : "Hello world"